### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by Zir0-93**

### CODE REVIEW

**Comment by Zir0-93** [comment]
@clarity-team diff

**Comment by ghost** [comment]
@clarity-team diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Pull request closed without merging**
